"""
CSV Seeding Script for Supabase / PostgreSQL.

Reads all 14 CSV files from vijul-engine/data/, parses types and NULL values cleanly
(preserving IFCT missing carbs and fiber as NULL rather than 0), and generates a
complete, runnable supabase/seed.sql while also supporting direct Supabase table insertion.
"""

from __future__ import annotations

import csv
import os
import sys
from pathlib import Path
from typing import Any, Optional

# Locate directories
CURRENT_DIR = Path(__file__).resolve().parent
BACKEND_DIR = CURRENT_DIR.parent
PROJECT_ROOT = BACKEND_DIR.parent
VIJUL_DATA_DIR = Path(
    os.getenv("VIJUL_ENGINE_PATH", str(PROJECT_ROOT.parent / "vijul-engine"))
).resolve() / "data"

OUTPUT_SQL_FILE = PROJECT_ROOT / "supabase" / "seed.sql"


def parse_csv_value(val: str, field_name: str) -> Any:
    if val is None:
        return None
    val = str(val).strip()
    if val == "" or val.lower() in ("null", "none", "na", "n/a"):
        return None

    # Handle boolean fields
    if val.lower() in ("true", "1", "yes"):
        return True
    if val.lower() in ("false", "0", "no"):
        return False

    # Handle numbers
    try:
        if "." in val:
            return float(val)
        return int(val)
    except ValueError:
        return val


def sql_format(val: Any) -> str:
    if val is None:
        return "NULL"
    if isinstance(val, bool):
        return "TRUE" if val else "FALSE"
    if isinstance(val, (int, float)):
        return str(val)
    # String escaping
    escaped = str(val).replace("'", "''")
    return f"'{escaped}'"


def load_csv_rows(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        print(f"[Warning] CSV file not found: {path}")
        return []
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        return [
            {k: parse_csv_value(v, k) for k, v in row.items()}
            for row in reader
        ]


def generate_seed_sql() -> None:
    print(f"Reading CSV data from: {VIJUL_DATA_DIR}")
    sql_statements: list[str] = [
        "-- ====================================================================",
        "-- UniFit Static Engine Seed Data",
        "-- Auto-generated by backend/scripts/seed_csv_to_supabase.py",
        "-- ====================================================================\n",
    ]

    # Map tables to CSV files
    table_csv_map = [
        ("foods", VIJUL_DATA_DIR / "processed" / "foods_100_final.csv"),
        ("meals", VIJUL_DATA_DIR / "processed" / "meals.csv"),
        ("meal_items", VIJUL_DATA_DIR / "processed" / "meal_items.csv"),
        ("activities", VIJUL_DATA_DIR / "workouts" / "activities.csv"),
        ("workout_templates", VIJUL_DATA_DIR / "workouts" / "workout_templates.csv"),
        ("exercise_variations", VIJUL_DATA_DIR / "workouts" / "exercise_variations.csv"),
        ("strength_session_items", VIJUL_DATA_DIR / "workouts" / "strength_session_items.csv"),
        ("lifestyle_schedule_rules", VIJUL_DATA_DIR / "workouts" / "lifestyle_schedule_rules.csv"),
        ("progression_rules", VIJUL_DATA_DIR / "workouts" / "progression_rules.csv"),
        ("accessibility_profiles", VIJUL_DATA_DIR / "workouts" / "accessibility_profiles.csv"),
        ("accessibility_resources", VIJUL_DATA_DIR / "workouts" / "accessibility_resources.csv"),
        ("accessibility_workout_templates", VIJUL_DATA_DIR / "workouts" / "accessibility_workout_templates.csv"),
        ("accessibility_exercise_guidance", VIJUL_DATA_DIR / "workouts" / "accessibility_exercise_guidance.csv"),
        ("accessibility_progression_rules", VIJUL_DATA_DIR / "workouts" / "accessibility_progression_rules.csv"),
    ]

    total_inserted = 0

    for table_name, csv_path in table_csv_map:
        rows = load_csv_rows(csv_path)
        if not rows:
            continue

        columns = list(rows[0].keys())
        cols_str = ", ".join(columns)

        sql_statements.append(f"-- Seeding {table_name} ({len(rows)} records)")
        sql_statements.append(f"INSERT INTO public.{table_name} ({cols_str}) VALUES")

        value_lines = []
        for row in rows:
            formatted_vals = [sql_format(row.get(col)) for col in columns]
            value_lines.append(f"  ({', '.join(formatted_vals)})")

        sql_statements.append(",\n".join(value_lines))
        sql_statements.append("ON CONFLICT DO NOTHING;\n")
        total_inserted += len(rows)

    OUTPUT_SQL_FILE.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT_SQL_FILE.open("w", encoding="utf-8") as f:
        f.write("\n".join(sql_statements))

    print(f"Successfully generated: {OUTPUT_SQL_FILE} with {total_inserted} total records across 14 tables.")


if __name__ == "__main__":
    generate_seed_sql()
